version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./pdfs:/app/pdfs
      - ./logs:/app/logs
    environment:
      - DATABASE_URL=sqlite:///invoice_system.db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
